name: Tests & Coverage
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Cache conda
        uses: actions/cache@v2.1.1
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ hashFiles('environment-ci.yml') }}

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.7.0
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: pydna_test_environment
          channels: conda-forge, defaults
          environment-file: environment.yml
          use-only-tar-bz2: true

      - name: globstar
        shell: bash -l {0}
        run: bash shopt -s globstar

      - name: test notebooks
        shell: bash -l {0}
        run: pytest --current-env --capture=no --nbval **/*.ipynb

      - name: Upload coverage to Codecov
        if: (matrix.codecov)
        uses: codecov/codecov-action@v1.0.13
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
